services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: ./apirest
    ports:
      - 8080:8080
    depends_on:
      - db